config/routes.rb
Rails.application.routes.draw do
  resources :ccs
  root "ccs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cc.rb
class Cc < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ccs_controller.rb
class CcsController < ApplicationController
  before_action :set_cc, only: %i[ show edit update destroy ]

  # GET /ccs or /ccs.json
  def index
    @ccs = Cc.all
  end

  # GET /ccs/1 or /ccs/1.json
  def show
  end

  # GET /ccs/new
  def new
    @cc = Cc.new
  end

  # GET /ccs/1/edit
  def edit
  end

  # POST /ccs or /ccs.json
  def create
    @cc = Cc.new(cc_params)

    respond_to do |format|
      if @cc.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.update("cc_list", partial: "ccs/cc_list", locals: {css: @css})
        end
        format.html { redirect_to ccs_path, notice: "Cc was successfully created." }
        format.json { render :show, status: :created, location: @cc }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ccs/1 or /ccs/1.json
  def update
    respond_to do |format|
      if @cc.update(cc_params)
        format.html { redirect_to cc_url(@cc), notice: "Cc was successfully updated." }
        format.json { render :show, status: :ok, location: @cc }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ccs/1 or /ccs/1.json
  def destroy
    @cc.destroy

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update("cc_list", partial: "ccs/cc_list", locals: {css: @css})
      end
      format.html { redirect_to ccs_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cc
      @cc = Cc.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cc_params
      params.require(:cc).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ccs_helper.rb
module CcsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/ccs/_cc_list.html.erb
<% ccs = Cc.all %>

<div class="tags">
  <% ccs.each do |cc| %>
   <span class="tag is-medium is-primary is-light"><%= cc.email %>

     <%= link_to '<button class="delete is-small">""</button>.html_safe', cc, method: :delete, class: "delete is-small" %>

   </span>
  <% end %>
</div>

app/views/ccs/_form.html.erb
<%= form_with(model: cc, local: true, data: { turbo_frame: 'emails' }) do |form| %>
  <% if cc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cc.errors.count, "error") %> prohibited this cc from being saved:</h2>

      <ul>
        <% cc.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ccs/edit.html.erb
<h1>Editing Cc</h1>

<%= render 'form', cc: @cc %>

<%= link_to 'Show', @cc %> |
<%= link_to 'Back', ccs_path %>

app/views/ccs/index.html.erb
<h1 class="title">CCs</h1>

<div class="columns">

  <div class="column is-one-third">
    <%= turbo_frame_tag "cc_input" do %>
      <%= link_to "New CC", new_cc_path %>
      <hr>
    <% end %>

    <%= turbo_frame_tag "cc_list" do %>
      <div id="cc_list">
        <%= render "cc_list" %>
      </div>
    <% end %>
  </div>
  <div class="column">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/mCdA4bJAGGk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  </div>
</div>

app/views/ccs/new.html.erb
<h1>Add Ccs</h1>

<%= turbo_frame_tag "cc_input" do %>

  <%= form_with model: @cc, data: { controller: :ccs, action: "turbo:submit-end->reset-form#reset" } do |f| %>

    <div class="field">
      <p class="label">Email:</p>
        <div class="is-flex">
          <%= f.text_field :email, class: "input", placeholder: "recipient address", :required => true %>
          <%= f.submit "✓", class: "button is-primary mx-2" %><%= link_to "✖", ccs_path, class: "button is-danger" %>
        </div>
    </div>

  <% end %>
  <hr>
<% end %>

app/views/ccs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @cc.email %>
</p>

<%= link_to 'Edit', edit_cc_path(@cc) %> |
<%= link_to 'Back', ccs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CcForm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>